# Generated by Django 4.2.7 on 2026-01-03 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_remove_uploadedimage_user_input'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='documents_found',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='images',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='sources',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='web_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='bot_response',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='user_input',
            field=models.TextField(),
        ),
    ]
